name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install
          echo "Dependencies installed successfully."

      - name: Build the project
        run: |
          npm run build
          echo "Project built successfully."

      - name: Debug information
        run: |
          echo "Checking directory structure"
          ls -la
          echo "Checking branch"
          git branch
          echo "Checking git status"
          git status

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_history: false
